<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="SimpleNV.version.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>KerbVisionIR</RootNamespace>
    <AssemblyName>KerbVisionIR</AssemblyName>
    <TargetFramework>net4.8</TargetFramework>
    <DefineConstants>UNITY_STANDALONE, UNITY_2017_1_OR_NEWER, UNITY_2017_2_OR_NEWER, UNITY_2017_3_OR_NEWER, UNITY_2018_1_OR_NEWER, UNITY_2018_2_OR_NEWER, UNITY_2018_3_OR_NEWER, UNITY_2019_1_OR_NEWER, UNITY_2019_2_OR_NEWER, UNITY_2019_3_OR_NEWER, ENABLE_VR_MODULE, ENABLE_VR</DefineConstants>
  </PropertyGroup>
  <PropertyGroup>
    <BinariesOutputRelativePath>GameData\SimpleNV\Plugins</BinariesOutputRelativePath>
    <GenerateKSPAssemblyAttribute>true</GenerateKSPAssemblyAttribute>
    <GenerateKSPAssemblyDependencyAttributes>true</GenerateKSPAssemblyDependencyAttributes>
  </PropertyGroup>
  <ItemGroup>
    <KSPVersionFile Include="$(RepoRootPath)\GameData\SimpleNV\SimpleNV.version">
      <Destination>$(RepoRootPath)\GameData\SimpleNV\SimpleNV.version</Destination>
      <KSP_Version_Min>1.12.3</KSP_Version_Min>
    </KSPVersionFile>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ClickThroughBlocker">
      <HintPath>$(KSPRoot)\GameData\000_ClickThroughBlocker\Plugins\ClickThroughBlocker.dll</HintPath>
      <Private>false</Private>
      <CKANIdentifier>ClickThroughBlocker</CKANIdentifier>
      <KSPAssemblyVersion>1.0</KSPAssemblyVersion>
    </Reference>
    <Reference Include="ToolbarControl">
      <HintPath>$(KSPRoot)\GameData\001_ToolbarControl\Plugins\ToolbarControl.dll</HintPath>
      <Private>false</Private>
      <CKANIdentifier>ToolbarController</CKANIdentifier>
      <KSPAssemblyName>ToolbarController</KSPAssemblyName>
      <KSPAssemblyVersion>1.0</KSPAssemblyVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\.editorconfig">
      <Link>.editorconfig</Link>
    </None>
    <None Include="PostProcessing\.editorconfig" />
    <None Include="PostProcessing\Unity.Postprocessing.Runtime.asmdef" />
    <None Include="SimpleNV.csproj.user" />
  </ItemGroup>
  <ItemGroup>
    <Publicize Include="Assembly-CSharp" IncludeCompilerGeneratedMembers="false" />
  </ItemGroup>
  <PropertyGroup>
    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    <PublicizeAsReferenceAssemblies>false</PublicizeAsReferenceAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="KSPBuildTools" Version="0.0.4" />
  </ItemGroup>
</Project>
